source 'http://rubygems.org'

ruby '2.1.5'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-redis'
gem 'rubyzip'
gem 'bcrypt'
gem 'uuid'
gem 'sinatra-cross_origin'
gem 'faye-websocket'
gem 'gravatar-ultimate'
gem 'pony'
gem 'rest-client'
gem 'pg'
gem 'rufus-scheduler'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'resque'
gem 'rake'
gem 'faker'
gem 'week_of_month', '~> 1.2.3.2'
gem 'PriorityQueue', '~> 0.1.2'
gem 'pqueue'

group :development do
  gem 'sqlite3'
  gem 'shotgun'
end
