
require_relative 'appointment'
require_relative 'dashboard_record'
require_relative 'event/event'
require_relative 'event/Daily'
require_relative 'event/Weekly'
require_relative 'event/Monthly'
require_relative 'event/Yearly'
require_relative 'invitation'
require_relative 'local_avatar'
require_relative 'notification'
require_relative 'plugin'
require_relative 'team'
require_relative 'team_appointment'
require_relative 'team_snapshot'
require_relative 'teams_relations'
require_relative 'user'
require_relative 'users_teams'